import { StyleSheet } from 'react-native';

export default StyleSheet.create ({
  frame: {
    flex: 1,
    backgroundColor: '#FFE1BD',
    padding: 12,
  },
  backgroundImage: {
    flex: 1,
    overflow: 'hidden',
  },
  imageStyle: {
    borderRadius: 20,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  count: {
    fontFamily: 'PixelifySans-Bold',
    fontSize: 22,
    color: '#3E2723',
    textAlign: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  countNum: {
    fontWeight: '600',
    fontStyle: 'italic',
    fontSize: 30,
  },
  timerLabel: {
    fontFamily: 'PixelifySans-Bold',
    fontSize: 18,
    color: '#8F2A1E',
    textAlign: 'center',
    marginBottom: 10,
  },
  hero: {
    marginTop: 10,
    marginBottom: 20,
  },
  tomato: {
    width: 210,
    height: 210,
    resizeMode: 'contain',
  },
  timerBox: {
    width: '80%',
    maxWidth: 320,
    height: 100,
    marginVertical: 12,
    backgroundColor: '#fff9f2',
    borderWidth: 4,
    borderColor: '#E7B983',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerDigits: {
    fontFamily: 'PressStart2P-Regular',
    fontSize: 50,
    letterSpacing: 4,
    color: '#3E2723',
    textAlign: 'center',
    includeFontPadding: false,
  },
  cta: {
    marginTop: 30,
    width: '100%',
    alignItems: 'center',
  },
  btnStart: {
    width: 240,
    height: 54,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ED5345',
    backgroundColor: '#FFE4E4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  btnStop: {
    width: 240,
    height: 54,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ED5345',
    backgroundColor: '#FFE4E4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  btnPauseResume: {
    width: 240,
    height: 54,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ED5345',
    backgroundColor: '#FFE4E4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  btnGroup: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    marginBottom: 25,
    width: '100%',
    flexWrap: 'wrap',
  },
  breakButtonGroup: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 25,
    width: '100%',
  },
  btnControl: {
    width: 110,
    height: 54,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ED5345',
    backgroundColor: '#FFE4E4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  btnText: {
    color: '#8F2A1E',
    fontFamily: 'PixelifySans-Bold',
    fontSize: 20,
    letterSpacing: 1,
    textAlign: 'center',
  },
});