import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  frame: {
    flex: 1,
    backgroundColor: '#FFE1BD',
    padding: 12,
  },
  scrollViewStyle: {
    flexGrow: 1,
  },
  title: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',

    padding: 10,
    borderRadius: 12,
    marginBottom: 14,
  },
  logoStyle: {
    width: 50,
    height: 50,
  },
  titleText: {
    fontSize: 30,
    color: '#000000',
    fontFamily: 'PixelifySans-Bold',
  },
  content: {
    borderRadius: 12,
    padding: 16,
  },
  label: {
    fontSize: 18,
    fontFamily: 'PixelifySans-Bold',
    color: '#3E2723',
    marginBottom: 8,
  },
  inputGroup: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  input: {
    flex: 1,
    height: 50,
    borderWidth: 2,
    borderColor: '#f4b871',
    borderRadius: 12,
    padding: 12,
    fontFamily: 'PressStart2P-Regular',
    fontSize: 14,
    backgroundColor: '#fff',
  },
  setButton: {
    color: '#861d0a',
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 10,
    justifyContent: 'center',
    height: 50,
    backgroundColor: '#ff6b6b',
    marginLeft: 8,
  },
  setButtonText: {
    color: 'white',
    fontFamily: 'PixelifySans-Bold',
    fontSize: 18,
  },
  selectContainer: {},
  selectOption: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#f4b871',
    backgroundColor: '#fff',
    marginTop: 8,
    alignItems: 'center',
  },
  selectOptionActive: {
    backgroundColor: '#ffdede',
    borderColor: '#f44527',
  },
  selectOptionText: {
    fontFamily: 'PressStart2P-Regular',
    fontSize: 10,
    color: '#3E2723',
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 15,
  },
  switchLabel: {
    fontSize: 18,
    fontFamily: 'PixelifySans-Bold',
    color: '#3E2723',
  },
  helpButton: {
    flex: 1,
    color: '#861d0a',
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#f44527',
    padding: 15,
    alignItems: 'center',
    backgroundColor: '#ff6b6b',
  },
  helpButtonText: {
    color: 'white',
    fontFamily: 'PixelifySans-Bold',
    fontSize: 18,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginTop: 10,
  },
  resourceButton: {
    flex: 1,
    backgroundColor: '#ff6b6b',
    color: '#861d0a',
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#f44527',
    padding: 15,
    alignItems: 'center',
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff6e7',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 20,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#f4b871',
  },
  modalTitle: {
    fontSize: 24,
    fontFamily: 'PixelifySans-Bold',
    color: '#3E2723',
  },
  closeButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffdede',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#f44527',
  },
  closeButtonText: {
    fontSize: 20,
    color: '#861d0a',
    fontFamily: 'PixelifySans-Bold',
  },
  faqList: {
    paddingHorizontal: 15,
    maxHeight: 300,
  },
  faqItem: {
    marginBottom: 15,
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#f4b871',
  },
  faqQuestion: {
    fontSize: 18,
    fontFamily: 'PixelifySans-Bold',
    color: '#3E2723',
    marginBottom: 8,
  },
  faqAnswer: {
    fontSize: 14,
    fontFamily: 'PixelifySans-Bold',
    color: '#5e5c5c',
    lineHeight: 18,
  },
  noResultsText: {
    fontSize: 14,
    fontFamily: 'PixelifySans-Bold',
    color: '#999',
    textAlign: 'center',
    marginTop: 20,
  },
  contactSection: {
    paddingHorizontal: 15,
    paddingTop: 15,
    borderTopWidth: 2,
    borderTopColor: '#f4b871',
  },
  contactTitle: {
    fontSize: 16,
    fontFamily: 'PixelifySans-Bold',
    color: '#3E2723',
    marginBottom: 10,
  },
  contactButton: {
    backgroundColor: '#ffdede',
    borderWidth: 3,
    borderColor: '#f44527',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
  },
  contactButtonText: {
    color: '#861d0a',
    fontFamily: 'PixelifySans-Bold',
    fontSize: 14,
  },
  resourceLinkText: {
    color: '#007AFF',
    fontSize: 17,
    fontFamily: 'PixelifySans-Bold',
  },
  errorText: {
    fontSize: 12,
    fontFamily: 'PixelifySans-Bold',
    color: '#d32f2f',
    marginBottom: 12,
    marginTop: -4,
  },
});
